version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flashtix_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flashtix_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin7576
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flashtix_network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: flashtix_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flashtix_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: flashtix_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Connection port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flashtix_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  flashtix_network:
    driver: bridge
